name: m3_dynamics
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - matplotlib
  - pandas
  - scipy
  - seaborn
  - jupyterlab
  - ipykernel
  # Herramientas de Visualizacion y Dashboard
  - plotly
  - streamlit
  # Herramientas de Calidad de CÃ³digo
  - black
  - flake8
  - pytest
